name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: |
        sudo apt install libsfml-dev \
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test \
        sudo apt install -y g++-11 
      
    - name: Build Cellular
      run: make
