name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive

    - name: Install dependencies
      run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get install g++-11  python3 pip libgtest-dev libsfml-dev

    - name: Build Cellular
      env: 
        CC: /usr/bin/gcc-11
        CXX: /usr/bin/g++-11
      run: cmake . && make
