name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install sfml
      run: sudo apt-get install -y libsfml-dev
    
    - name: Install sfml
      run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get install -y g++-11 
      
    - name: Build Cellular
      run: make
