name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get install python3 pip \
        pip install cpplint \
	sudo apt-get install -y libsfml-dev \
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get install -y g++-11 

    - name: Run Linter
      run: cpplint --recursive ./src/

    - name: Build Cellular
      env: 
        CC: /usr/bin/gcc-11
        CXX: /usr/bin/g++-11
      run: cmake . && make
